services:
  postgres:
    container_name: ${APP_PREFIX}-db
    image: postgres:18.4-alpine
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend

  redis:
    container_name: ${APP_PREFIX}-redis
    image: redis:8.8-alpine
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend

  redis-insight:
    container_name: ${APP_PREFIX}-redis-insight
    image: redis/redisinsight:3.6
    depends_on:
      - redis
    volumes:
      - redisinsight-data:/data
    restart: unless-stopped
    ports:
      - ${REDIS_INSIGHT_PORT}:5540
    networks:
      - backend

  mailpit:
    image: axllent/mailpit:v1.30
    restart: unless-stopped
    container_name: ${APP_PREFIX}-mail
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - backend

  otel-lgtm:
    container_name: ${APP_PREFIX}-otel-lgtm
    image: grafana/otel-lgtm:0.29.1
    environment:
      LGTM_MODES: local
      ENABLE_LOGS_ALL: true
      PROMETHEUS_EXTRA_ARGS: "--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_PERIOD}d" # auto delete data
      GF_PLUGINS_PREINSTALL: grafana-pyroscope-app
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    volumes:
      - otel-lgtm-data:/data
    restart: unless-stopped
    ports:
      - ${GRAFANA_PORT}:3000
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP HTTP receiver
    networks:
      - backend

volumes:
  postgres-data:
  redis-data:
  redisinsight-data:
  otel-lgtm-data:

networks:
  backend:
    driver: bridge
